### ISSUE TITLE
Quering on SSAS Tabular with Python

### ISSUE THREAD

**Issue by JonatanTorres** [yehoshuadimarsky/python-ssas#1]
Hello,
My Enterprise has SQL Server Enterprise with SSAS on Tabular mode.
How can I query the SSAS instance with Python?

Can you give me an example using your API?
Thank you!

**Comment by yehoshuadimarsky** [comment]
Hi Jonatan! Sorry for the delayed response, I just saw this... need to figure out notifictations for this repo.
Anyway, here's a code snippet to get you started, it's really quite simple:
```
In [1]: import ssas_api
   ...: 
   ...: conn = ssas_api.set_conn_string(
   ...:     ssas_server='<YOUR_SERVER>',
   ...:     db_name='<YOUR_DATABASE>',
   ...:     username='<USERNAME>',
   ...:     password='<PASSWORD>'
   ...: )

In [2]: dax_string = '''
   ...: //any valid DAX query
   ...: EVALUATE
   ...: CALCULATETABLE(MyTable)
   ...: '''

In [3]: df = ssas_api.get_DAX(connection_string=conn, dax_string=dax_string)
```
