### ISSUE TITLE
Can this code be used in order to connect to AAS as well? 

### ISSUE THREAD

**Issue by nisharncslabs** [yehoshuadimarsky/python-ssas#13]
Hi,

I am curious to know whether this code template can be used to connect to Azure Analysis Services as well as SQL Server Analysis Services since in the Quickstart it shows DAX queries being fired off against SSAS?

**Comment by yehoshuadimarsky** [comment]
yes both work. you will probably have to experiment with the connection strings, i'd recommend searching through Microsoft's API docs

**Comment by nisharncslabs** [comment]
I just noticed in the "**Solutions** section you have a few lines saying:
"**Note**: I've only been using Azure Analysis Services, so the code is designed for that regarding the URL of the server and authentication string."

So it this api for SSAS or AAS?  Also it should be possible to edit the connection string to account for Multifactor Authentication which is what is recommended for Azure Analysis Services anyway?
