### ISSUE TITLE
Create a pypi package please!

### ISSUE THREAD

**Issue by rogerpou** [yehoshuadimarsky/python-ssas#15]
Hey, i really thank you for this API because i was really looking for something related.
The maximum thing i found was: https://github.com/S-C-O-U-T/Pyadomd
but didn't work for Azure Analysis Services just for local models.

If i could import automatically the API from PyPI instead of putting the file on the same folder, would be really great! 

Again, Thank you!

**Comment by yehoshuadimarsky** [comment]
Thanks for the feedback. I could, but I don't want to take an opionated view on which parts of the SSAS .NET API to implement, I'd rather leave that to the end user.
