### ISSUE TITLE
Add more processing options

### ISSUE THREAD

**Issue by danielcastrocarlsberg** [yehoshuadimarsky/python-ssas#4]
This is not an issue, still I think more options on the refresh type would be great as you are already using Microsoft.AnalysisServices.Tabular namespace.

Enum for refresh types is available here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.refreshtype?view=analysisservices-dotnet

Thanks for making this available!

**Comment by yehoshuadimarsky** [comment]
Feel free to extend this, it wasn't part of my use case...
