### ISSUE TITLE
On procecssing model/table/partitions define MaxParallelism

### ISSUE THREAD

**Issue by danielcastrocarlsberg** [yehoshuadimarsky/python-ssas#5]
When invoking SaveChanges it would be better if we could define the maximum parallelism for SSAS to process the objects.

This attribute is available within SaveOptions object:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.analysisservices.tabular.model.savechanges?view=analysisservices-dotnet

Also this method could be adapted to support receiving an array of objects for example (partitions) and these would be processed in parallel.

**Comment by yehoshuadimarsky** [comment]
Feel free to extend this, it wasn't part of my use case...
