### ISSUE TITLE
Minor Error on QuickStart

### ISSUE THREAD

**Issue by Ambivalance** [yehoshuadimarsky/python-ssas#6]
QuickStart Sample Code:
.....
conn = ssas_api.set_conn_string(
    ssas_server='<YOUR_SERVER>',
    db_name='<YOUR_DATABASE>',
    username='<USERNAME>',
    password='<PASSWORD>'
)
.....

the first server parameter name should change to simply "server",not "ssas_server"

conn = ssas_api.set_conn_string(
    server='<YOUR_SERVER>',
    db_name='<YOUR_DATABASE>',
    username='<USERNAME>',
    password='<PASSWORD>'
)

thanks by the way~

**Comment by yehoshuadimarsky** [comment]
fixed, thanks
