### ISSUE TITLE
server instead of ssas_server

### ISSUE THREAD

**Issue by pawarbi** [yehoshuadimarsky/python-ssas#7]
In the example, it should be server instead of ssas_server

import ssas_api
   ...: 
   ...: conn = ssas_api.set_conn_string(
   ...:     **ssas_server**='<YOUR_SERVER>',
   ...:     db_name='<YOUR_DATABASE>',
   ...:     username='<USERNAME>',
   ...:     password='<PASSWORD>'
   ...: )

**Comment by yehoshuadimarsky** [comment]
fixed, thanks
